-- Every remaining US state gets a form template row.
--
-- Generated by scripts/generate-state-templates.py from researched state
-- documentation rules, on 2026-09-08. Regenerate rather than
-- hand-editing: the generator is where the tiering rule lives.
--
-- ===========================================================================
-- READ THIS BEFORE SELLING ANYTHING ON THE BACK OF IT
-- ===========================================================================
--
-- These rows are NOT state-issued forms. Across all fifty states and DC,
-- exactly one publishes a document a provider fills in for progress notes:
-- West Virginia, and that one is hand-authored in 0041 rather than
-- generated here. Virginia was long believed to be a second — it is not;
-- see 0040. What a state publishes, if anything, is a rule saying what
-- documentation must contain, leaving the layout to the provider.
--
-- So the rows below come in two tiers, and the tier is visible on the page.
--
-- TIER 1 — 20 state(s) whose citation was independently verified.
--   scripts/verify-citations.py fetched the state's own code site, confirmed
--   the rule number appears there, and confirmed a verbatim quotation from
--   the rule appears there too. The footer cites the rule and says plainly
--   that it is not a state-issued form.
--     US-AK  Alaska                 7 AAC 105.230
--            https://aws.state.ak.us/OnlinePublicNotices/Notices/Attachment.aspx?id=112295
--     US-AR  Arkansas               Arkansas Medicaid Provider Manual, Section II — DDS Community and Employment Supports (CES) Waiver, § 202.100
--            https://humanservices.arkansas.gov/wp-content/uploads/171108_DDSACS_II.doc
--     US-CA  California             Cal. Code Regs. tit. 17, § 56026
--            https://www.dds.ca.gov/wp-content/uploads/2025/06/FinalRegulationText.pdf
--     US-GA  Georgia                DBHDD Provider Manual for Community Developmental Disability Providers, FY2027 Q1, Part I.E (Individual Record) — progress notes and event notes
--            https://dbhdd.org/files/Provider-Manual-DD.pdf
--     US-HI  Hawaii                 Hawaiʻi 1915(c) HCBS Medicaid Waiver for Individuals with Intellectual and Developmental Disabilities, Waiver Provider Standards Manual § 3.10.A (Documentation Requirements for All Claims) and § 3.7.D (Maintenance of Participant Records)
--            https://health.hawaii.gov/ddd/files/2026/06/Waiver-Provider-Standards-Manual-July2026.pdf
--     US-IA  Iowa                   Iowa Admin. Code r. 441—24.4(4)
--            https://www.legis.iowa.gov/docs/iac/chapter/441.24.pdf
--     US-IN  Indiana                460 IAC 6-24-2 (with 460 IAC 6-17-2, 6-17-3 and 6-17-4)
--            https://www.in.gov/fssa/ddars/files/460-IAC-6.PDF
--     US-KY  Kentucky               907 KAR 12:010, Section 4(15)(g)(2)(a)
--            https://apps.legislature.ky.gov/law/kar/titles/907/012/010/
--     US-MA  Massachusetts          115 CMR 4.00 (specifically 4.04(2)(a) Progress Notes; 4.03(2) General Requirements)
--            https://www.sec.state.ma.us/reg_pub/pdf/100/115004.pdf
--     US-MO  Missouri               13 CSR 70-3.030(2)(A)
--            https://www.sos.mo.gov/cmsimages/adrules/csr/current/13csr/13c70-3.pdf
--     US-MS  Mississippi            Miss. Admin. Code Title 23, Part 208, Rule 5.10
--            https://medicaid.ms.gov/wp-content/uploads/2025/07/Title-23-Part-208-HCBS-LTC-eff.-7.1.2025.pdf
--     US-NC  North Carolina         NC DHHS DMH/DD/SUS Record Management and Documentation Manual (APSM 45-2), Chapter 6 'Documentation and Service Notes'; underlying rule 10A NCAC 27G .0206
--            https://www.ncdhhs.gov/rmdmjuly-2025/download
--     US-NH  New Hampshire          N.H. Code Admin. R. He-M 1001.08
--            https://gc.nh.gov/rules/state_agencies/he-m1000.html
--     US-NJ  New Jersey             N.J.A.C. 10:44A-4.3(b); see also N.J.A.C. 10:44A-2.9
--            https://nj.gov/humanservices/notices/documents/rules-and-regulations/NJAC%2010_44A%20STANDARDS%20FOR%20COMMUNITY%20RESIDENCES%20FOR%20INDIVIDUALS%20WITH%20DEVELOPMENTAL%20DISABILITIES.PDF
--     US-NV  Nevada                 Nevada Medicaid Services Manual (MSM) Chapter 2100, § 2103.2A(5)
--            https://www.nevadamedicaid.nv.gov/uploadedFiles/dhcfpnvgov/content/Resources/AdminSupport/Manuals/MSM/C2100/MSM_2100_25_04_01.pdf
--     US-NY  New York               OPWDD Administrative Memorandum (ADM) #2014-01
--            https://opwdd.ny.gov/system/files/documents/2020/01/admin_memo_2014-01.pdf
--     US-PA  Pennsylvania           55 Pa. Code § 6100.226; 55 Pa. Code § 6100.227
--            https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/055/chapter6100/s6100.226.html&d=reduce
--     US-RI  Rhode Island           212-RICR-10-00-1, § 1.19
--            https://rules.sos.ri.gov/regulations/part/212-10-00-1
--     US-SC  South Carolina         SC DDSN Residential Habilitation Standards, RH8.0-RH8.1 (Documentation)
--            https://ddsn.sc.gov/sites/ddsn/files/PublicDocuments/Finance%20and%20Audit%20Resources/Residential%20Habilitation%20Standards%20-%20Revised%20(061820).pdf
--     US-TX  Texas                  Texas HHSC, Home and Community-based Services (HCS) Program Billing Requirements, Sections 3810 (General Requirements), 3820 (Written Service Log and Written Summary Log), 3850 (Example Forms) and 4560 (Residential Support Subcomponent)
--            https://fhb.hhs.texas.gov/sites/default/files/documents/hcs-billing-requirements.pdf
--
-- TIER 2 — 28 state(s) shipping with no citation at all.
--   Either no rule was found, or what was found could not be verified against
--   the state's own site. These print exactly what the GENERIC template
--   prints: a complete, defensible progress note that names no state and
--   cites no rule. That is the honest output for a rule nobody has read, and
--   it is materially better than the alternative -- an agency in one state
--   filing a document that carries another state's form number.
--
--   An agency in a tier 2 state can still sign up and work. Nothing about
--   their document is wrong; it simply makes no regulatory claim.
--
-- WHAT SALES MAY SAY
--   Tier 1: "we file to your state's rule, and here is the rule."
--   Tier 2: "we'll build your state in if you're first."
--   Neither tier may ever be described as "we have your state's form".
--
-- Rules change. Every citation here was checked on the generation date above
-- and has not been re-checked since. Whoever sells into a tier 1 state should
-- re-read the rule first.
--
-- `schema` is selected from the GENERIC row rather than copied, so all of
-- these share one body of prompts and grounding vocabulary.

-- US-AK Alaska (tier 1)
--   7 AAC 105.230 — https://aws.state.ak.us/OnlinePublicNotices/Notices/Attachment.aspx?id=112295
--   effective 2018-06-07
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000301'::uuid, null, 'daily_progress_note_ak_v2', 2,
  'Daily Progress Note', null, 'US-AK', 'Alaska',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 7 AAC 105.230. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 7 AAC 105.230. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000301'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000301'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-AK';

-- US-AL Alabama (tier 2)
--   no citation: researcher recorded no note-content requirements from this rule
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000202'::uuid, null, 'daily_progress_note_al', 1,
  'Daily Progress Note', null, 'US-AL', 'Alabama',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-AR Arkansas (tier 1)
--   Arkansas Medicaid Provider Manual, Section II — DDS Community and Employment Supports (CES) Waiver, § 202.100 — https://humanservices.arkansas.gov/wp-content/uploads/171108_DDSACS_II.doc
--   effective 2017-08-22
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000303'::uuid, null, 'daily_progress_note_ar_v2', 2,
  'Daily Progress Note', null, 'US-AR', 'Arkansas',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Arkansas Medicaid Provider Manual, Section II — DDS Community and Employment Supports (CES) Waiver, § 202.100. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Arkansas Medicaid Provider Manual, Section II — DDS Community and Employment Supports (CES) Waiver, § 202.100. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000303'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000303'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-AR';

-- US-AZ Arizona (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'enumerated data points above are the quarterly summary, not the per-shift note'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000204'::uuid, null, 'daily_progress_note_az', 1,
  'Daily Progress Note', null, 'US-AZ', 'Arizona',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-CA California (tier 1)
--   Cal. Code Regs. tit. 17, § 56026 — https://www.dds.ca.gov/wp-content/uploads/2025/06/FinalRegulationText.pdf
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000305'::uuid, null, 'daily_progress_note_ca_v2', 2,
  'Daily Progress Note', null, 'US-CA', 'California',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Cal. Code Regs. tit. 17, § 56026. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Cal. Code Regs. tit. 17, § 56026. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000305'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000305'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-CA';

-- US-CO Colorado (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'not enumerate a per-shift progress-note'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000206'::uuid, null, 'daily_progress_note_co', 1,
  'Daily Progress Note', null, 'US-CO', 'Colorado',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-CT Connecticut (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'NOT mandate a per-resident, per-shift progress note'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000207'::uuid, null, 'daily_progress_note_ct', 1,
  'Daily Progress Note', null, 'US-CT', 'Connecticut',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-DC District of Columbia (tier 2)
--   no citation: page contains none of the rule numbers 1909.2
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000208'::uuid, null, 'daily_progress_note_dc', 1,
  'Daily Progress Note', null, 'US-DC', 'District of Columbia',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-DE Delaware (tier 2)
--   no citation: not claimed as read
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000209'::uuid, null, 'daily_progress_note_de', 1,
  'Daily Progress Note', null, 'US-DE', 'Delaware',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-FL Florida (tier 2)
--   no citation: only 0/32 of the quoted phrases appear on the cited page
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000210'::uuid, null, 'daily_progress_note_fl', 1,
  'Daily Progress Note', null, 'US-FL', 'Florida',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-GA Georgia (tier 1)
--   DBHDD Provider Manual for Community Developmental Disability Providers, FY2027 Q1, Part I.E (Individual Record) — progress notes and event notes — https://dbhdd.org/files/Provider-Manual-DD.pdf
--   effective 2026-07-01
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000311'::uuid, null, 'daily_progress_note_ga_v2', 2,
  'Daily Progress Note', null, 'US-GA', 'Georgia',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy DBHDD Provider Manual for Community Developmental Disability Providers, FY2027 Q1, Part I.E (Individual Record) — progress notes and event notes. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy DBHDD Provider Manual for Community Developmental Disability Providers, FY2027 Q1, Part I.E (Individual Record) — progress notes and event notes. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000311'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000311'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-GA';

-- US-HI Hawaii (tier 1)
--   Hawaiʻi 1915(c) HCBS Medicaid Waiver for Individuals with Intellectual and Developmental Disabilities, Waiver Provider Standards Manual § 3.10.A (Documentation Requirements for All Claims) and § 3.7.D (Maintenance of Participant Records) — https://health.hawaii.gov/ddd/files/2026/06/Waiver-Provider-Standards-Manual-July2026.pdf
--   effective 2026-07-01
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000312'::uuid, null, 'daily_progress_note_hi_v2', 2,
  'Daily Progress Note', null, 'US-HI', 'Hawaii',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Hawaiʻi 1915(c) HCBS Medicaid Waiver for Individuals with Intellectual and Developmental Disabilities, Waiver Provider Standards Manual § 3.10.A (Documentation Requirements for All Claims) and § 3.7.D (Maintenance of Participant Records). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Hawaiʻi 1915(c) HCBS Medicaid Waiver for Individuals with Intellectual and Developmental Disabilities, Waiver Provider Standards Manual § 3.10.A (Documentation Requirements for All Claims) and § 3.7.D (Maintenance of Participant Records). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000312'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000312'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-HI';

-- US-IA Iowa (tier 1)
--   Iowa Admin. Code r. 441—24.4(4) — https://www.legis.iowa.gov/docs/iac/chapter/441.24.pdf
--   effective Version stamped IAC 2/5/25
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000313'::uuid, null, 'daily_progress_note_ia_v2', 2,
  'Daily Progress Note', null, 'US-IA', 'Iowa',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Iowa Admin. Code r. 441—24.4(4). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Iowa Admin. Code r. 441—24.4(4). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000313'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000313'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-IA';

-- US-ID Idaho (tier 2)
--   no citation: page contains none of the rule numbers 16.03.21.301.04
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000214'::uuid, null, 'daily_progress_note_id', 1,
  'Daily Progress Note', null, 'US-ID', 'Idaho',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-IL Illinois (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'no section enumerating the contents of a per-shift DSP note'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000215'::uuid, null, 'daily_progress_note_il', 1,
  'Daily Progress Note', null, 'US-IL', 'Illinois',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-IN Indiana (tier 1)
--   460 IAC 6-24-2 (with 460 IAC 6-17-2, 6-17-3 and 6-17-4) — https://www.in.gov/fssa/ddars/files/460-IAC-6.PDF
--   effective 460 IAC 6-24-2 filed Nov 4, 2002 (26 IR 779); amended filed Aug 29, 2003 (27 IR 114); readopted filed Aug 11, 2014 (20140910-IR-460140241RFA)
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000316'::uuid, null, 'daily_progress_note_in_v2', 2,
  'Daily Progress Note', null, 'US-IN', 'Indiana',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 460 IAC 6-24-2 (with 460 IAC 6-17-2, 6-17-3 and 6-17-4). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 460 IAC 6-24-2 (with 460 IAC 6-17-2, 6-17-3 and 6-17-4). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000316'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000316'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-IN';

-- US-KS Kansas (tier 2)
--   no citation: not claimed as read
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000217'::uuid, null, 'daily_progress_note_ks', 1,
  'Daily Progress Note', null, 'US-KS', 'Kansas',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-KY Kentucky (tier 1)
--   907 KAR 12:010, Section 4(15)(g)(2)(a) — https://apps.legislature.ky.gov/law/kar/titles/907/012/010/
--   effective eff. 2-1-2013; amended eff. 6-3-2016; Cert. eff. 5-9-2023
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000318'::uuid, null, 'daily_progress_note_ky_v2', 2,
  'Daily Progress Note', null, 'US-KY', 'Kentucky',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 907 KAR 12:010, Section 4(15)(g)(2)(a). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 907 KAR 12:010, Section 4(15)(g)(2)(a). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000318'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000318'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-KY';

-- US-LA Louisiana (tier 2)
--   no citation: not a state-run domain: www.lamedicaid.com
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000219'::uuid, null, 'daily_progress_note_la', 1,
  'Daily Progress Note', null, 'US-LA', 'Louisiana',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-MA Massachusetts (tier 1)
--   115 CMR 4.00 (specifically 4.04(2)(a) Progress Notes; 4.03(2) General Requirements) — https://www.sec.state.ma.us/reg_pub/pdf/100/115004.pdf
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000320'::uuid, null, 'daily_progress_note_ma_v2', 2,
  'Daily Progress Note', null, 'US-MA', 'Massachusetts',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 115 CMR 4.00 (specifically 4.04(2)(a) Progress Notes; 4.03(2) General Requirements). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 115 CMR 4.00 (specifically 4.04(2)(a) Progress Notes; 4.03(2) General Requirements). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000320'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000320'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-MA';

-- US-MD Maryland (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'NOT enumerate per-shift note content'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000221'::uuid, null, 'daily_progress_note_md', 1,
  'Daily Progress Note', null, 'US-MD', 'Maryland',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-ME Maine (tier 2)
--   no citation: page contains none of the rule numbers 10-144, 21.09
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000222'::uuid, null, 'daily_progress_note_me', 1,
  'Daily Progress Note', null, 'US-ME', 'Maine',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-MI Michigan (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'NOT enumerate per-shift progress note content'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000223'::uuid, null, 'daily_progress_note_mi', 1,
  'Daily Progress Note', null, 'US-MI', 'Michigan',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-MN Minnesota (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'notes be kept but does NOT prescribe'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000224'::uuid, null, 'daily_progress_note_mn', 1,
  'Daily Progress Note', null, 'US-MN', 'Minnesota',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-MO Missouri (tier 1)
--   13 CSR 70-3.030(2)(A) — https://www.sos.mo.gov/cmsimages/adrules/csr/current/13csr/13c70-3.pdf
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000325'::uuid, null, 'daily_progress_note_mo_v2', 2,
  'Daily Progress Note', null, 'US-MO', 'Missouri',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 13 CSR 70-3.030(2)(A). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 13 CSR 70-3.030(2)(A). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000325'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000325'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-MO';

-- US-MS Mississippi (tier 1)
--   Miss. Admin. Code Title 23, Part 208, Rule 5.10 — https://medicaid.ms.gov/wp-content/uploads/2025/07/Title-23-Part-208-HCBS-LTC-eff.-7.1.2025.pdf
--   effective Part 208 published effective 7/1/2025; Rule 5.10 history: 'Revised to reflect changes with ID/DD Waiver renewal (eff. 07/01/2013) eff. 09/01/2015'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000326'::uuid, null, 'daily_progress_note_ms_v2', 2,
  'Daily Progress Note', null, 'US-MS', 'Mississippi',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Miss. Admin. Code Title 23, Part 208, Rule 5.10. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Miss. Admin. Code Title 23, Part 208, Rule 5.10. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000326'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000326'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-MS';

-- US-MT Montana (tier 2)
--   no citation: citation names no rule number to check: "Montana Developmental Disabilities Program Services Manual, 'Documentation' section (DPHHS, Behavioral Health and Developmental Disabilities Division)"
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000227'::uuid, null, 'daily_progress_note_mt', 1,
  'Daily Progress Note', null, 'US-MT', 'Montana',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-NC North Carolina (tier 1)
--   NC DHHS DMH/DD/SUS Record Management and Documentation Manual (APSM 45-2), Chapter 6 'Documentation and Service Notes'; underlying rule 10A NCAC 27G .0206 — https://www.ncdhhs.gov/rmdmjuly-2025/download
--   effective Manual effective July 8, 2025. 10A NCAC 27G .0206 eff. May 1, 1996; recodified Jan. 3, 2001; readopted without substantive public interest eff. July 20, 2019.
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000328'::uuid, null, 'daily_progress_note_nc_v2', 2,
  'Daily Progress Note', null, 'US-NC', 'North Carolina',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy NC DHHS DMH/DD/SUS Record Management and Documentation Manual (APSM 45-2), Chapter 6 ''Documentation and Service Notes''; underlying rule 10A NCAC 27G .0206. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy NC DHHS DMH/DD/SUS Record Management and Documentation Manual (APSM 45-2), Chapter 6 ''Documentation and Service Notes''; underlying rule 10A NCAC 27G .0206. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000328'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000328'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-NC';

-- US-ND North Dakota (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'NO rule enumerating the content of a per-shift/daily progress note'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000229'::uuid, null, 'daily_progress_note_nd', 1,
  'Daily Progress Note', null, 'US-ND', 'North Dakota',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-NE Nebraska (tier 2)
--   no citation: not claimed as read
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000230'::uuid, null, 'daily_progress_note_ne', 1,
  'Daily Progress Note', null, 'US-NE', 'Nebraska',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-NH New Hampshire (tier 1)
--   N.H. Code Admin. R. He-M 1001.08 — https://gc.nh.gov/rules/state_agencies/he-m1000.html
--   effective Document #14255, eff. 5-23-25 (expires 5-23-35); prior #12775, eff. 5-7-19
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000331'::uuid, null, 'daily_progress_note_nh_v2', 2,
  'Daily Progress Note', null, 'US-NH', 'New Hampshire',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy N.H. Code Admin. R. He-M 1001.08. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy N.H. Code Admin. R. He-M 1001.08. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000331'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000331'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-NH';

-- US-NJ New Jersey (tier 1)
--   N.J.A.C. 10:44A-4.3(b); see also N.J.A.C. 10:44A-2.9 — https://nj.gov/humanservices/notices/documents/rules-and-regulations/NJAC%2010_44A%20STANDARDS%20FOR%20COMMUNITY%20RESIDENCES%20FOR%20INDIVIDUALS%20WITH%20DEVELOPMENTAL%20DISABILITIES.PDF
--   effective Chapter readopted effective March 29, 2019; 10:44A-2.9 amended by R.2023 d.021 effective February 6, 2023
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000332'::uuid, null, 'daily_progress_note_nj_v2', 2,
  'Daily Progress Note', null, 'US-NJ', 'New Jersey',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy N.J.A.C. 10:44A-4.3(b); see also N.J.A.C. 10:44A-2.9. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy N.J.A.C. 10:44A-4.3(b); see also N.J.A.C. 10:44A-2.9. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000332'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000332'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-NJ';

-- US-NM New Mexico (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'NO enumerated service-note content'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000233'::uuid, null, 'daily_progress_note_nm', 1,
  'Daily Progress Note', null, 'US-NM', 'New Mexico',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-NV Nevada (tier 1)
--   Nevada Medicaid Services Manual (MSM) Chapter 2100, § 2103.2A(5) — https://www.nevadamedicaid.nv.gov/uploadedFiles/dhcfpnvgov/content/Resources/AdminSupport/Manuals/MSM/C2100/MSM_2100_25_04_01.pdf
--   effective April 1, 2025 (MTL 09/25; transmittal letter dated March 25, 2025)
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000334'::uuid, null, 'daily_progress_note_nv_v2', 2,
  'Daily Progress Note', null, 'US-NV', 'Nevada',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Nevada Medicaid Services Manual (MSM) Chapter 2100, § 2103.2A(5). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Nevada Medicaid Services Manual (MSM) Chapter 2100, § 2103.2A(5). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000334'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000334'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-NV';

-- US-NY New York (tier 1)
--   OPWDD Administrative Memorandum (ADM) #2014-01 — https://opwdd.ny.gov/system/files/documents/2020/01/admin_memo_2014-01.pdf
--   effective July 1, 2014
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000335'::uuid, null, 'daily_progress_note_ny_v2', 2,
  'Daily Progress Note', null, 'US-NY', 'New York',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy OPWDD Administrative Memorandum (ADM) #2014-01. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy OPWDD Administrative Memorandum (ADM) #2014-01. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000335'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000335'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-NY';

-- US-OK Oklahoma (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'NO rule enumerating the content of a daily I/DD service note'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000236'::uuid, null, 'daily_progress_note_ok', 1,
  'Daily Progress Note', null, 'US-OK', 'Oklahoma',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-OR Oregon (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'not an enumerated note-content'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000237'::uuid, null, 'daily_progress_note_or', 1,
  'Daily Progress Note', null, 'US-OR', 'Oregon',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-PA Pennsylvania (tier 1)
--   55 Pa. Code § 6100.226; 55 Pa. Code § 6100.227 — https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/055/chapter6100/s6100.226.html&d=reduce
--   effective Text current through 56 Pa.B. 4026 (July 4, 2026) as published by the Pennsylvania Code and Bulletin
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000338'::uuid, null, 'daily_progress_note_pa_v2', 2,
  'Daily Progress Note', null, 'US-PA', 'Pennsylvania',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 55 Pa. Code § 6100.226; 55 Pa. Code § 6100.227. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 55 Pa. Code § 6100.226; 55 Pa. Code § 6100.227. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000338'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000338'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-PA';

-- US-RI Rhode Island (tier 1)
--   212-RICR-10-00-1, § 1.19 — https://rules.sos.ri.gov/regulations/part/212-10-00-1
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000339'::uuid, null, 'daily_progress_note_ri_v2', 2,
  'Daily Progress Note', null, 'US-RI', 'Rhode Island',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 212-RICR-10-00-1, § 1.19. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy 212-RICR-10-00-1, § 1.19. Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000339'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000339'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-RI';

-- US-SC South Carolina (tier 1)
--   SC DDSN Residential Habilitation Standards, RH8.0-RH8.1 (Documentation) — https://ddsn.sc.gov/sites/ddsn/files/PublicDocuments/Finance%20and%20Audit%20Resources/Residential%20Habilitation%20Standards%20-%20Revised%20(061820).pdf
--   effective Revised June 18, 2020
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000340'::uuid, null, 'daily_progress_note_sc_v2', 2,
  'Daily Progress Note', null, 'US-SC', 'South Carolina',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy SC DDSN Residential Habilitation Standards, RH8.0-RH8.1 (Documentation). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy SC DDSN Residential Habilitation Standards, RH8.0-RH8.1 (Documentation). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000340'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000340'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-SC';

-- US-SD South Dakota (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: "describes the contents of the participant's record, not the contents of a per-shift progre"
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000241'::uuid, null, 'daily_progress_note_sd', 1,
  'Daily Progress Note', null, 'US-SD', 'South Dakota',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-TN Tennessee (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'NOT prescribe the contents of a per-shift/daily note'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000242'::uuid, null, 'daily_progress_note_tn', 1,
  'Daily Progress Note', null, 'US-TN', 'Tennessee',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-TX Texas (tier 1)
--   Texas HHSC, Home and Community-based Services (HCS) Program Billing Requirements, Sections 3810 (General Requirements), 3820 (Written Service Log and Written Summary Log), 3850 (Example Forms) and 4560 (Residential Support Subcomponent) — https://fhb.hhs.texas.gov/sites/default/files/documents/hcs-billing-requirements.pdf
--   effective Revision 25-1, effective January 1, 2025 (Section 3820 is Revision 24-1, effective January 1, 2024; Section 4560 residential support is Revision 21-3, effective September 1, 2021)
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000343'::uuid, null, 'daily_progress_note_tx_v2', 2,
  'Daily Progress Note', null, 'US-TX', 'Texas',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Texas HHSC, Home and Community-based Services (HCS) Program Billing Requirements, Sections 3810 (General Requirements), 3820 (Written Service Log and Written Summary Log), 3850 (Example Forms) and 4560 (Residential Support Subcomponent). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
update ghh.form_templates set
  render_config = '{"page": {"size": "LETTER", "margin": 42, "padding_bottom": 100}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note", "legal_citation": "Layout built to satisfy Texas HHSC, Home and Community-based Services (HCS) Program Billing Requirements, Sections 3810 (General Requirements), 3820 (Written Service Log and Written Summary Log), 3850 (Example Forms) and 4560 (Residential Support Subcomponent). Not a state-issued form."}, "narrative_min_height": 340}'::jsonb,
  updated_at = now()
 where id = '00000000-0000-0000-0000-000000000343'::uuid;
update ghh.form_templates set
  active = (id = '00000000-0000-0000-0000-000000000343'::uuid), updated_at = now()
 where org_id is null and jurisdiction = 'US-TX';

-- US-UT Utah (tier 2)
--   no citation: not claimed as read
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000244'::uuid, null, 'daily_progress_note_ut', 1,
  'Daily Progress Note', null, 'US-UT', 'Utah',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-VT Vermont (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'NOT enumerate the contents of a daily/shift service note'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000245'::uuid, null, 'daily_progress_note_vt', 1,
  'Daily Progress Note', null, 'US-VT', 'Vermont',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-WA Washington (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'NOT enumerate what a progress note'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000246'::uuid, null, 'daily_progress_note_wa', 1,
  'Daily Progress Note', null, 'US-WA', 'Washington',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-WI Wisconsin (tier 2)
--   no citation: researcher wrote that this rule does not describe note content: 'specifies record CONTENTS, not the contents of a per-shift progress note'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000247'::uuid, null, 'daily_progress_note_wi', 1,
  'Daily Progress Note', null, 'US-WI', 'Wisconsin',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-WY Wyoming (tier 2)
--   no citation: citation names no rule number to check: 'Wyoming Medicaid Rules, Chapter 45, Section 8 (Documentation Standards); see also Chapter 45, Section 7 (Provider Recordkeeping and Data Collection)'
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000248'::uuid, null, 'daily_progress_note_wy', 1,
  'Daily Progress Note', null, 'US-WY', 'Wyoming',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
