-- Every remaining US state gets a form template row.
--
-- Generated by scripts/generate-state-templates.py from researched state
-- documentation rules, on 2026-09-07. Regenerate rather than
-- hand-editing: the generator is where the tiering rule lives.
--
-- ===========================================================================
-- READ THIS BEFORE SELLING ANYTHING ON THE BACK OF IT
-- ===========================================================================
--
-- These rows are NOT fifty state-issued forms. Almost no state publishes one;
-- Virginia's DBHDS Form #680 is the exception, not the pattern. What a state
-- publishes, if anything, is a rule saying what service documentation must
-- contain, and the layout is left to the provider.
--
-- So the rows below come in two tiers, and the tier is visible on the page.
--
-- TIER 1 — 0 state(s) whose citation was independently verified.
--   scripts/verify-citations.py fetched the state's own code site, confirmed
--   the rule number appears there, and confirmed a verbatim quotation from
--   the rule appears there too. The footer cites the rule and says plainly
--   that it is not a state-issued form.
--     (none survived verification)
--
-- TIER 2 — 49 state(s) shipping with no citation at all.
--   Either no rule was found, or what was found could not be verified against
--   the state's own site. These print exactly what the GENERIC template
--   prints: a complete, defensible progress note that names no state and
--   cites no rule. That is the honest output for a rule nobody has read, and
--   it is materially better than the alternative -- an agency in one state
--   filing a document that carries another state's form number.
--
--   An agency in a tier 2 state can still sign up and work. Nothing about
--   their document is wrong; it simply makes no regulatory claim.
--
-- WHAT SALES MAY SAY
--   Tier 1: "we file to your state's rule, and here is the rule."
--   Tier 2: "we'll build your state in if you're first."
--   Neither tier may ever be described as "we have your state's form".
--
-- Rules change. Every citation here was checked on the generation date above
-- and has not been re-checked since. Whoever sells into a tier 1 state should
-- re-read the rule first.
--
-- `schema` is selected from the GENERIC row rather than copied, so all of
-- these share one body of prompts and grounding vocabulary.

-- US-AK Alaska (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000201'::uuid, null, 'daily_progress_note_ak', 1,
  'Daily Progress Note', null, 'US-AK', 'Alaska',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-AL Alabama (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000202'::uuid, null, 'daily_progress_note_al', 1,
  'Daily Progress Note', null, 'US-AL', 'Alabama',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-AR Arkansas (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000203'::uuid, null, 'daily_progress_note_ar', 1,
  'Daily Progress Note', null, 'US-AR', 'Arkansas',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-AZ Arizona (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000204'::uuid, null, 'daily_progress_note_az', 1,
  'Daily Progress Note', null, 'US-AZ', 'Arizona',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-CA California (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000205'::uuid, null, 'daily_progress_note_ca', 1,
  'Daily Progress Note', null, 'US-CA', 'California',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-CO Colorado (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000206'::uuid, null, 'daily_progress_note_co', 1,
  'Daily Progress Note', null, 'US-CO', 'Colorado',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-CT Connecticut (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000207'::uuid, null, 'daily_progress_note_ct', 1,
  'Daily Progress Note', null, 'US-CT', 'Connecticut',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-DC District of Columbia (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000208'::uuid, null, 'daily_progress_note_dc', 1,
  'Daily Progress Note', null, 'US-DC', 'District of Columbia',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-DE Delaware (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000209'::uuid, null, 'daily_progress_note_de', 1,
  'Daily Progress Note', null, 'US-DE', 'Delaware',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-FL Florida (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000210'::uuid, null, 'daily_progress_note_fl', 1,
  'Daily Progress Note', null, 'US-FL', 'Florida',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-GA Georgia (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000211'::uuid, null, 'daily_progress_note_ga', 1,
  'Daily Progress Note', null, 'US-GA', 'Georgia',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-HI Hawaii (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000212'::uuid, null, 'daily_progress_note_hi', 1,
  'Daily Progress Note', null, 'US-HI', 'Hawaii',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-IA Iowa (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000213'::uuid, null, 'daily_progress_note_ia', 1,
  'Daily Progress Note', null, 'US-IA', 'Iowa',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-ID Idaho (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000214'::uuid, null, 'daily_progress_note_id', 1,
  'Daily Progress Note', null, 'US-ID', 'Idaho',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-IL Illinois (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000215'::uuid, null, 'daily_progress_note_il', 1,
  'Daily Progress Note', null, 'US-IL', 'Illinois',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-IN Indiana (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000216'::uuid, null, 'daily_progress_note_in', 1,
  'Daily Progress Note', null, 'US-IN', 'Indiana',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-KS Kansas (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000217'::uuid, null, 'daily_progress_note_ks', 1,
  'Daily Progress Note', null, 'US-KS', 'Kansas',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-KY Kentucky (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000218'::uuid, null, 'daily_progress_note_ky', 1,
  'Daily Progress Note', null, 'US-KY', 'Kentucky',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-LA Louisiana (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000219'::uuid, null, 'daily_progress_note_la', 1,
  'Daily Progress Note', null, 'US-LA', 'Louisiana',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-MA Massachusetts (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000220'::uuid, null, 'daily_progress_note_ma', 1,
  'Daily Progress Note', null, 'US-MA', 'Massachusetts',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-MD Maryland (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000221'::uuid, null, 'daily_progress_note_md', 1,
  'Daily Progress Note', null, 'US-MD', 'Maryland',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-ME Maine (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000222'::uuid, null, 'daily_progress_note_me', 1,
  'Daily Progress Note', null, 'US-ME', 'Maine',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-MI Michigan (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000223'::uuid, null, 'daily_progress_note_mi', 1,
  'Daily Progress Note', null, 'US-MI', 'Michigan',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-MN Minnesota (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000224'::uuid, null, 'daily_progress_note_mn', 1,
  'Daily Progress Note', null, 'US-MN', 'Minnesota',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-MO Missouri (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000225'::uuid, null, 'daily_progress_note_mo', 1,
  'Daily Progress Note', null, 'US-MO', 'Missouri',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-MS Mississippi (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000226'::uuid, null, 'daily_progress_note_ms', 1,
  'Daily Progress Note', null, 'US-MS', 'Mississippi',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-MT Montana (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000227'::uuid, null, 'daily_progress_note_mt', 1,
  'Daily Progress Note', null, 'US-MT', 'Montana',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-NC North Carolina (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000228'::uuid, null, 'daily_progress_note_nc', 1,
  'Daily Progress Note', null, 'US-NC', 'North Carolina',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-ND North Dakota (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000229'::uuid, null, 'daily_progress_note_nd', 1,
  'Daily Progress Note', null, 'US-ND', 'North Dakota',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-NE Nebraska (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000230'::uuid, null, 'daily_progress_note_ne', 1,
  'Daily Progress Note', null, 'US-NE', 'Nebraska',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-NH New Hampshire (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000231'::uuid, null, 'daily_progress_note_nh', 1,
  'Daily Progress Note', null, 'US-NH', 'New Hampshire',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-NJ New Jersey (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000232'::uuid, null, 'daily_progress_note_nj', 1,
  'Daily Progress Note', null, 'US-NJ', 'New Jersey',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-NM New Mexico (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000233'::uuid, null, 'daily_progress_note_nm', 1,
  'Daily Progress Note', null, 'US-NM', 'New Mexico',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-NV Nevada (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000234'::uuid, null, 'daily_progress_note_nv', 1,
  'Daily Progress Note', null, 'US-NV', 'Nevada',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-NY New York (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000235'::uuid, null, 'daily_progress_note_ny', 1,
  'Daily Progress Note', null, 'US-NY', 'New York',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-OK Oklahoma (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000236'::uuid, null, 'daily_progress_note_ok', 1,
  'Daily Progress Note', null, 'US-OK', 'Oklahoma',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-OR Oregon (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000237'::uuid, null, 'daily_progress_note_or', 1,
  'Daily Progress Note', null, 'US-OR', 'Oregon',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-PA Pennsylvania (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000238'::uuid, null, 'daily_progress_note_pa', 1,
  'Daily Progress Note', null, 'US-PA', 'Pennsylvania',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-RI Rhode Island (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000239'::uuid, null, 'daily_progress_note_ri', 1,
  'Daily Progress Note', null, 'US-RI', 'Rhode Island',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-SC South Carolina (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000240'::uuid, null, 'daily_progress_note_sc', 1,
  'Daily Progress Note', null, 'US-SC', 'South Carolina',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-SD South Dakota (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000241'::uuid, null, 'daily_progress_note_sd', 1,
  'Daily Progress Note', null, 'US-SD', 'South Dakota',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-TN Tennessee (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000242'::uuid, null, 'daily_progress_note_tn', 1,
  'Daily Progress Note', null, 'US-TN', 'Tennessee',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-TX Texas (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000243'::uuid, null, 'daily_progress_note_tx', 1,
  'Daily Progress Note', null, 'US-TX', 'Texas',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-UT Utah (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000244'::uuid, null, 'daily_progress_note_ut', 1,
  'Daily Progress Note', null, 'US-UT', 'Utah',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-VT Vermont (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000245'::uuid, null, 'daily_progress_note_vt', 1,
  'Daily Progress Note', null, 'US-VT', 'Vermont',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-WA Washington (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000246'::uuid, null, 'daily_progress_note_wa', 1,
  'Daily Progress Note', null, 'US-WA', 'Washington',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-WI Wisconsin (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000247'::uuid, null, 'daily_progress_note_wi', 1,
  'Daily Progress Note', null, 'US-WI', 'Wisconsin',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-WV West Virginia (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000248'::uuid, null, 'daily_progress_note_wv', 1,
  'Daily Progress Note', null, 'US-WV', 'West Virginia',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;

-- US-WY Wyoming (tier 2)
--   no rule located; ships as the generic note
insert into ghh.form_templates (
  id, org_id, key, version, name, form_number, jurisdiction,
  jurisdiction_name, schema, render_config
)
select
  '00000000-0000-0000-0000-000000000249'::uuid, null, 'daily_progress_note_wy', 1,
  'Daily Progress Note', null, 'US-WY', 'Wyoming',
  g.schema,
  '{"page": {"size": "LETTER", "margin": 42}, "header": {"title": "Daily Progress Note"}, "footer": {"form_line": "Daily Progress Note"}, "narrative_min_height": 340}'::jsonb
from ghh.form_templates g
where g.key = 'daily_progress_note_generic' and g.org_id is null
on conflict (id) do nothing;
